# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationlink',
            name='created_by',
        ),
    ]
