# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organizationlink_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationlink',
            name='link',
            field=models.URLField(),
        ),
    ]
